name: KCore
main: pl.kuezese.core.CorePlugin
authors: [ 'kuezese' ]
version: '1.1.0'
description: 'All-in-one plugin for your Minecraft server.'
depend: [ FunnyGuilds, LuckPerms, WorldEdit ]

commands:
  region:
    aliases: [ rg ]